# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_rss_config_dlg.ui'
#
# Created: Wed Feb 15 12:09:06 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_rss_config_dlg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(396, 280)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(396, 280))
        Dialog.setMaximumSize(QtCore.QSize(673, 406))
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinFrequence = QtGui.QSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFrequence.sizePolicy().hasHeightForWidth())
        self.spinFrequence.setSizePolicy(sizePolicy)
        self.spinFrequence.setMinimum(1)
        self.spinFrequence.setMaximum(120)
        self.spinFrequence.setProperty(_fromUtf8("value"), 15)
        self.spinFrequence.setObjectName(_fromUtf8("spinFrequence"))
        self.horizontalLayout_5.addWidget(self.spinFrequence)
        self.label_4 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinMax = QtGui.QSpinBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMax.sizePolicy().hasHeightForWidth())
        self.spinMax.setSizePolicy(sizePolicy)
        self.spinMax.setMinimum(2)
        self.spinMax.setMaximum(20)
        self.spinMax.setProperty(_fromUtf8("value"), 10)
        self.spinMax.setObjectName(_fromUtf8("spinMax"))
        self.horizontalLayout_4.addWidget(self.spinMax)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableUrls = QtGui.QTableWidget(Dialog)
        self.tableUrls.setMinimumSize(QtCore.QSize(0, 0))
        self.tableUrls.setWordWrap(False)
        self.tableUrls.setRowCount(2)
        self.tableUrls.setColumnCount(2)
        self.tableUrls.setObjectName(_fromUtf8("tableUrls"))
        self.tableUrls.setColumnCount(2)
        self.tableUrls.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableUrls.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableUrls.setHorizontalHeaderItem(1, item)
        self.tableUrls.horizontalHeader().setVisible(True)
        self.tableUrls.horizontalHeader().setCascadingSectionResizes(False)
        self.tableUrls.horizontalHeader().setDefaultSectionSize(100)
        self.tableUrls.horizontalHeader().setHighlightSections(True)
        self.tableUrls.horizontalHeader().setMinimumSectionSize(20)
        self.tableUrls.verticalHeader().setVisible(False)
        self.tableUrls.verticalHeader().setDefaultSectionSize(20)
        self.tableUrls.verticalHeader().setMinimumSectionSize(15)
        self.horizontalLayout.addWidget(self.tableUrls)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.btnAdd = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMinimumSize(QtCore.QSize(20, 20))
        self.btnAdd.setMaximumSize(QtCore.QSize(20, 20))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.verticalLayout_4.addWidget(self.btnAdd)
        self.btnRemove = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemove.sizePolicy().hasHeightForWidth())
        self.btnRemove.setSizePolicy(sizePolicy)
        self.btnRemove.setMinimumSize(QtCore.QSize(20, 20))
        self.btnRemove.setMaximumSize(QtCore.QSize(20, 20))
        self.btnRemove.setBaseSize(QtCore.QSize(20, 20))
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.verticalLayout_4.addWidget(self.btnRemove)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.btnOkCancel = QtGui.QDialogButtonBox(Dialog)
        self.btnOkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.btnOkCancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.btnOkCancel.setObjectName(_fromUtf8("btnOkCancel"))
        self.verticalLayout_3.addWidget(self.btnOkCancel)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.btnOkCancel, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.btnOkCancel, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "RSS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Fréquence :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Nombre d\'éléments max : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Abonnements :", None, QtGui.QApplication.UnicodeUTF8))
        self.tableUrls.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Nom", None, QtGui.QApplication.UnicodeUTF8))
        self.tableUrls.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))

